---
- name: check nvm shell script
  stat:
    path: "{{ nvm_install_path }}/nvm.sh"
  register: nvm_sh

- name: check npm version
  stat:
    path: "{{ nvm_npm_path }}"
  register: npm_sh

- block:
  - file:
      path: "{{ nvm_home }}/.bashrc"
      state: touch
      mode: 0644
      owner: "{{ nvm_user }}"
      group: "{{ nvm_group }}"
    
  - name: install apt prerequisites
    apt:
      name: curl
      update_cache: true
      state: present

  - name: install nvm
    shell: curl -o- https://raw.githubusercontent.com/creationix/nvm/{{ nvm_version }}/install.sh | /bin/bash
    become: yes
    become_user: "{{ nvm_user }}"
    environment:
      HOME: "{{ nvm_home }}"

  - name: install node version and set it as default
    shell: ". {{ nvm_home }}/.nvm/nvm.sh && nvm install {{ nvm_node_version }} && nvm use {{ nvm_node_version }}"
    become: yes
    become_user: "{{ nvm_user }}"
    args:
      executable: /bin/bash
    environment:
      HOME: "{{ nvm_home }}"

  when: nvm_sh.stat.exists == False or npm_sh.stat.exists == False
